### ISSUE TITLE
syntax not working

### ISSUE THREAD

**Issue by ghosttie** [jtorjo/logwizard#42]
The first ten lines of my log file are:

`2015/12/21 18:26:50.888 01150-1c18 DEV: (jadserv) Version 7.1.5 - ANSI, OS Version: NT 6.01 build 7601 (Service Pack 1), Wow64: false, Architecture: x64-msoft-win64-ansi
2015/12/21 18:26:50.888 01150-1c18 DEV: Invocation: "D:\filevision\dev\5.7\bin\jadserv.exe" path="D:\filevision\dev\5.7\system" ini="D:/filevision/dev/5.7/system/jade.ini" service="FileVision57DevDBServer" run
2015/12/21 18:26:50.888 01150-1c18 JomLog: JDI conversions are enabled
2015/12/21 18:26:50.904 01150-1c18 JomService: createJadeDBService for JadeServer FileVision57 Dev DB Server
2015/12/21 18:26:50.904 011ec-1264 DEV: (jadeSentinel) Version 7.1.5 - ANSI, OS Version: NT 6.01 build 7601 (Service Pack 1), Wow64: false, Architecture: x64-msoft-win64-ansi
2015/12/21 18:26:51.013 011ec-1264 DEV: Invocation: "D:\filevision\dev\5.7\bin\jadeSentinel.exe" pid=4432 prefix=jadserv ini="D:/filevision/dev/5.7/system/jade.ini"    
2015/12/21 18:26:51.013 01150-1da4 SvcMgr: Level:Info Source:FileVision57DevDBServer Message:Jade service 'FileVision57DevDBServer' is starting.
2015/12/21 18:26:51.169 01150-1da4 RPCMgr2: RPCManager::createInstance: 17612F0-1-7192-SVR creates 1763830-1-109-RPC
2015/12/21 18:26:51.309 01150-1da4 RPCMgr2: TransportIdlePollInterval = 120000 ms
2015/12/21 18:26:51.418 01150-1da4 RPCMgr2: ServerConnectionGroup 1 = HPSM,Enabled,Global\FVDev57`

and my syntax is:

`$date[0, ' '] $time['', ' '] $ctx1['', ' '] $ctx2['', ' '] $msg`

**Comment by jtorjo** [comment]
will look into it
