### ISSUE TITLE
Crash import logfile

### ISSUE THREAD

**Issue by matidio** [jtorjo/logwizard#87]
Logwizard crashes importing attached logfile. Type Part-per-line. Settings are reset to default
Win7 64, LogWizard version 1.8.16
If you need any further information let me know
[cntlm.zip](https://github.com/jtorjo/logwizard/files/206238/cntlm.zip)

**Comment by jtorjo** [comment]
thanks! will take a look later this week

**Comment by jtorjo** [comment]
@matidio I just looked at the log. Long story short, it's an extremely weird log file.
I will look to see what I can do - but the syntax is weird, to say the least.
I will get back to you ASAP

**Comment by matidio** [comment]
Don't worry about the log. I thought it would be more important to you avoid the crashes. Shouldn't happen ...
Anyway if you need some information let me know

**Comment by jtorjo** [comment]
Agreed about the crashes - I will definitely fix that
